server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'

#spring.cloud.stream.bindingRetryInterval: 5

spring.cloud.stream.bindings.output:
  destination: downloaded-ads
  producer:
    headerMode: raw

spring.cloud.stream.bindings.input:
  destination: download-request
  group: download-request
  consumer:
    concurrency: 20
    headerMode: raw

spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: sync-demo
            configuration:
              num.stream.threads: 20
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            brokers: 192.168.2.61:32770, 192.168.2.61:32771
